### ISSUE TITLE
Disable Dialog Box?

### ISSUE THREAD

**Issue by Poiuy69** [primaeval/plugin.video.stream.searcher#3]
I like stream searcher but, if a stream fails, the search results are gone and you have to redo the search. I notice in playlist player, when the dialog box is disabled in settings, the search results remain after a failed stream.  Is it possible to add this setting to stream searcher too?  Thank you for your excellent addons :)

**Comment by primaeval** [comment]
The Refresh Folders Period setting is how many hours to cache the results of a channel search. Is that what you need?

**Comment by Poiuy69** [comment]
No, that works fine. I'd like to be able to view the search results in a directory, rather than a dialog box.

**Comment by primaeval** [comment]
I added a Setting to switch between dialog and directory in Channels. See if that is what you want.

**Comment by Poiuy69** [comment]
That works great. Thank you so much :)
